### ISSUE TITLE
ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by SrikanthBhandary** [MrLeeh/pdftools#1]
I got an error while mergng pdfs in Python 3.

  File "C:\Python34\lib\site-packages\PyPDF2\utils.py", line 149, in **getitem**
    len_self = len(self)
  File "C:\Python34\lib\site-packages\PyPDF2\utils.py", line 140, in **len**
    return self.lengthFunction()
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 983, in getNumPages
    self._flatten()
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 1281, in _flatten
    pages = catalog["/Pages"].getObject()
  File "C:\Python34\lib\site-packages\PyPDF2\generic.py", line 501, in __getitem__
    return dict.**getitem**(self, key).getObject()
  File "C:\Python34\lib\site-packages\PyPDF2\generic.py", line 177, in getObject
    return self.pdf.getObject(self).getObject()
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 1366, in getObject
    retval = self._getObjectFromStream(indirectReference)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 1320, in _getObjectFromStream
    objnum = NumberObject.readFromStream(streamData)
  File "C:\Python34\lib\site-packages\PyPDF2\generic.py", line 264, in readFromStream
    return NumberObject(num)
  File "C:\Python34\lib\site-packages\PyPDF2\generic.py", line 251, in __new__
    return int.**new**(cls, value)
ValueError: invalid literal for int() with base 10: b''

**Comment by stlehmann** [comment]
Can you text me the command line call you used for this to happen?.

**Comment by SrikanthBhandary** [comment]
Hi Lehmann,

Greeting for the day!

Sorry for the delayed response. I was using your PDF tools and it was very
good. Unfortunately I could not able  to merge the pdf's through your tool
and also with the following code. Further I am guessing this might be

an issue with pypdf2 library. Sorry for the inconvenience caused. Could you
please help me to resolve this issue?

import os
from PyPDF2 import PdfFileReader, PdfFileMerger

files_dir = " "   # this is the path for pdf
pdf_files = [f for f in os.listdir(files_dir) if f.endswith("pdf")]
merger = PdfFileMerger()

for filename in pdf_files:
    merger.append(PdfFileReader(os.path.join(files_dir, filename), "rb"))

merger.write(os.path.join(files_dir, "merged_full.pdf"))

_Trace :_

ValueError                                Traceback (most recent call
last)<ipython-input-1-6c2c9ea6fa46> in <module>()      7       8 for
filename in pdf_files:----> 9
merger.append(PdfFileReader(os.path.join(files_dir, filename), "rb"))
   10      11 merger.write(os.path.join(files_dir, "merged_full.pdf"))
C:\Python34\lib\site-packages\PyPDF2\merger.py in append(self,
fileobj, bookmark, pages, import_bookmarks)    196         """    197
--> 198         self.merge(len(self.pages), fileobj, bookmark, pages,
import_bookmarks)    199     200     def write(self, fileobj):
C:\Python34\lib\site-packages\PyPDF2\merger.py in merge(self,
position, fileobj, bookmark, pages, import_bookmarks)    132         #
Find the range of pages to merge.    133         if pages == None:-->
134             pages = (0, pdfr.getNumPages())    135         elif
isinstance(pages, PageRange):    136             pages =
pages.indices(pdfr.getNumPages())
C:\Python34\lib\site-packages\PyPDF2\pdf.py in getNumPages(self)
981         else:    982             if self.flattenedPages ==
None:--> 983                 self._flatten()    984             return
len(self.flattenedPages)    985
C:\Python34\lib\site-packages\PyPDF2\pdf.py in _flatten(self, pages,
inherit, indirectRef)   1279             self.flattenedPages = []
1280             catalog = self.trailer["/Root"].getObject()-> 1281
         pages = catalog["/Pages"].getObject()   1282    1283
t = "/Pages"
C:\Python34\lib\site-packages\PyPDF2\generic.py in __getitem__(self,
key)    499     500     def **getitem**(self, key):--> 501
return dict.**getitem**(self, key).getObject()    502     503     ##
C:\Python34\lib\site-packages\PyPDF2\generic.py in getObject(self)
175     176     def getObject(self):--> 177         return
self.pdf.getObject(self).getObject()    178     179     def
**repr**(self):
C:\Python34\lib\site-packages\PyPDF2\pdf.py in getObject(self,
indirectReference)   1364         if indirectReference.generation == 0
and \   1365                         indirectReference.idnum in
self.xref_objStm:-> 1366             retval =
self._getObjectFromStream(indirectReference)   1367         elif
indirectReference.generation in self.xref and \   1368
indirectReference.idnum in self.xref[indirectReference.generation]:
C:\Python34\lib\site-packages\PyPDF2\pdf.py in
_getObjectFromStream(self, indirectReference)   1318
streamData = BytesIO(b_(objStm.getData()))   1319         for i in
range(objStm['/N']):-> 1320             objnum =
NumberObject.readFromStream(streamData)   1321
readNonWhitespace(streamData)   1322             streamData.seek(-1,
1)
C:\Python34\lib\site-packages\PyPDF2\generic.py in
readFromStream(stream)    262             return FloatObject(num)
263         else:--> 264             return NumberObject(num)    265
  readFromStream = staticmethod(readFromStream)    266
C:\Python34\lib\site-packages\PyPDF2\generic.py in **new**(cls, value)
   249     250     def **new**(cls, value):--> 251         return
int.**new**(cls, value)    252     253     def as_numeric(self):
ValueError: invalid literal for int() with base 10: b''

On Sat, May 23, 2015 at 12:22 AM, Stefan Lehmann notifications@github.com
wrote:

> Can you text me the command line call you used for this to happen?.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MrLeeh/pdftools/issues/1#issuecomment-104742495.

## 

_Warm Regards,Srikanth Bhandary_

**Comment by stlehmann** [comment]
If you use your script and still get the Error it must be an issue in PyPDF2. Unfortunately I cannot help you much there. 

The only thing I have in mind is making a methodic approach in identifiying what is causing the problem. How many files are you merging? Can you identify a specific document causing the error? Maybe start with only two, this should work. Then increase the number of merged files until the error occurs. Either the number or the file should cause the problem.

Greetings

**Comment by SrikanthBhandary** [comment]
Hello,

Greeting for the day!

Thank you for your suggestions.

I have tried to merge the other pdf's which is working fine but it is
giving the error for the files created through Antena House. I have tried
with the two files but it is not working. Finally I used the external pdf
merger tool to merge and it is worked for me. Thank you for your
suggestions.

Regards,
Srikanth

On Wed, May 27, 2015 at 12:45 AM, Stefan Lehmann notifications@github.com
wrote:

> If you use your script and still get the Error it must be an issue in
> PyPDF2. Unfortunately I cannot help you much there.
> 
> The only thing I have in mind is making a methodic approach in
> identifiying what is causing the problem. How many files are you merging?
> Can you identify a specific document causing the error? Maybe start with
> only two, this should work. Then increase the number of merged files until
> the error occurs. Either the number or the file should cause the problem.
> 
> Greetings
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MrLeeh/pdftools/issues/1#issuecomment-105638681.

## 

_Warm Regards,Srikanth Bhandary_
