### ISSUE TITLE
Reorder booklet

### ISSUE THREAD

**Issue by jirmed** [MrLeeh/pdftools#2]
Hello,

I tried to use pdftools/pdfposter to split a scanned image of an A4 booklet. The booklet has been unstapled and scanned like double sided A3. I used pdfposter -p 2x1A4 on it. The document got perfectly split into individual pages. The last step needed is to reorder the booklet into the original page order (1,2,3...). It would be great if you could add this function to the package.

Regards

Jiri

**Comment by stlehmann** [comment]
@jirmed In general for merging multiple files in one you can use _pdfmerge_. How do you determine the order of the files?

**Comment by jirmed** [comment]
Example: I have a booklet 40 pages A4 portrait. If I unstaple it I get 10 sheets A3 (4 pages each). I put it into an automatic duplex scanner and I get PDF with 20 landscape A3 pages. In my 40 pages example the (double)pages are 40/1,2/39,38/3,4/37,...,22/19,20/21. Using pdfposter -p 2x1A4 I get a new 40 pages document (A4 portrait) in order 40,1,2,39,38,3,4,37,...,22,19,20,21. The last step needed is to reorder the PDF in the original sequence (1,2,3,4,...,39,40)

**Comment by stlehmann** [comment]
Ah I get it. It seems you have a very specific usecase there. The scripts in this repository are intended for general everday use. So this usecase is not supported. I guess for you it would be best to write your own little Python script using [PyPdf2](https://github.com/mstamy2/PyPDF2) directly to achieve your desired behaviour.

**Comment by jirmed** [comment]
I think it is not such a very specific usercase. There is even a commercial (Win only) software that can do that (http://www.axpertsoft.com/booklet-to-normal-pdf/)

**Comment by stlehmann** [comment]
Haven' t had the need for it so far. But if you find it useful you' re very welcome to make a PR for the feature.
