### ISSUE TITLE
Consider use a universal endline: Unix

### ISSUE THREAD

**Issue by ryukinix** [MrLeeh/pdftools#4]
I installed from `pip install pdftools` and pdfmerge.py has ^M endlines (dos). Would be nice if this works without I need to fix that. Version used: 1.1.0.

**Comment by stlehmann** [comment]
Try the new release 1.1.1.  Line-Endings should fit now.

**Comment by ChristianRinn** [comment]
Version 1.1.3 from pip has ^M endlines again, so I can not run it directly from the command line as I get
```
pdfadd.py --help
/usr/bin/env: ‘python\r’: No such file or directory
```

**Comment by stlehmann** [comment]
Hm, this is annoying. I use Windows for work but Mac at home. So it seems like it sometimes mixes things up.

**Comment by stlehmann** [comment]
OK, I uploaded the package from my Mac now and double-checked the line-endings. Should work now. Please give a short feedback if I'm right :)

**Comment by ChristianRinn** [comment]
It works like a charm. Thank you for the quick fix. I assume you published the repo to pypi from your Windows machine where git (unfortunately) converts all line endings to CRLF by default (you can choose the default behaviour during installation). There are several ways to work around this issue. You could either set the line endings on checkout in the .gitattributes file of this repository or change to global unix-style line endings with your windows machine which would be my choice but ymmv.

**Comment by stlehmann** [comment]
Glad it works now. I normally check out unix-style on my Windows machine but it's possible that I mistakenly chose the wrong option for this repository. Thanks for the feedback.
