### ISSUE TITLE
Syntax error during installation process

### ISSUE THREAD

**Issue by ghost** [MrLeeh/pdftools#6]
Not sure if it affects anything
<details><summary>python setup.py install</summary>

root@dev-alex-02:/root/pdftools-1.0.8  # ./setup.py install
: No such file or directory

root@dev-alex-02:/root/pdftools-1.0.8  # python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to pdftools.egg-info/requires.txt
writing pdftools.egg-info/PKG-INFO
writing top-level names to pdftools.egg-info/top_level.txt
writing dependency_links to pdftools.egg-info/dependency_links.txt
reading manifest file 'pdftools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pdftools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pdftools
copying pdftools/__init__.py -> build/lib/pdftools
copying pdftools/pdftools.py -> build/lib/pdftools
copying pdftools/parseutil.py -> build/lib/pdftools
copying pdftools/_version.py -> build/lib/pdftools
UPDATING build/lib/pdftools/_version.py
set build/lib/pdftools/_version.py to '1.0.8'
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pdftools
copying build/lib/pdftools/__init__.py -> build/bdist.linux-x86_64/egg/pdftools
copying build/lib/pdftools/pdftools.py -> build/bdist.linux-x86_64/egg/pdftools
copying build/lib/pdftools/parseutil.py -> build/bdist.linux-x86_64/egg/pdftools
copying build/lib/pdftools/_version.py -> build/bdist.linux-x86_64/egg/pdftools
byte-compiling build/bdist.linux-x86_64/egg/pdftools/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pdftools/pdftools.py to pdftools.pyc
  File "build/bdist.linux-x86_64/egg/pdftools/pdftools.py", line 15
    def pdf_merge(inputs: [str], output: str, delete: bool=False):
                        ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pdftools/parseutil.py to parseutil.pyc
  File "build/bdist.linux-x86_64/egg/pdftools/parseutil.py", line 20
    def parse_rangearg(args, max_: int, min_: int=1):
                                 ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pdftools/_version.py to _version.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts

</details>

**Comment by stlehmann** [comment]
Which version of python are you using?

**Comment by ghost** [comment]
3.4

**Comment by stlehmann** [comment]
Please use the newest version of pdftools which is 1.1.4.

Use `git clone https://github.com/stlehmann/pdftools.git` or `pip install pdftools` to get the newest version.
